import { posthogAiBetaServerClient } from "@oakai/core/src/analytics/posthogAiBetaServerClient";
import { aiLogger } from "@oakai/logger";

import { placeholderQuiz } from "../../core/quiz/fixtures/placeholderQuestion";
import type { FullQuizService } from "../../core/quiz/interfaces";
import type {
  ExperimentalPatchDocument,
  PatchDocument,
} from "../../protocol/jsonPatchProtocol";
import type {
  LooseLessonPlan,
  Quiz,
  QuizQuestion,
} from "../../protocol/schema";

const log = aiLogger("aila:experimental-patches");

/**
 * Wrap a value in an experimental patch 'document'
 */
function preparePatch(
  value: ExperimentalPatchDocument["value"],
): ExperimentalPatchDocument {
  return {
    type: "experimentalPatch",
    value,
  };
}

function annotateQuestions(questions: QuizQuestion[]): QuizQuestion[] {
  return questions.map((question) => ({
    ...question,
    question: question.question + " Question generated by recommender method.",
  }));
}

/**
 * Fetch and enqueue experimental (agentic) additions
 */
export async function fetchExperimentalPatches({
  lessonPlan,
  llmPatches,
  handlePatch,
  fullQuizService,
  userId,
}: {
  lessonPlan: LooseLessonPlan;
  llmPatches: PatchDocument[];
  handlePatch: (patch: ExperimentalPatchDocument) => Promise<void>;
  fullQuizService: FullQuizService;
  userId?: string;
}) {
  if (lessonPlan.subject !== "maths") {
    // Only maths has experimental patches for now
    return;
  }

  if (!userId) {
    log.info("Experimental patches disabled or no user ID. Skipping.");
    return;
  }

  const mathsQuizzesEnabled = await posthogAiBetaServerClient.isFeatureEnabled(
    "maths-quiz-v0",
    userId,
  );

  if (!mathsQuizzesEnabled) {
    log.info("Maths quiz feature-flag disabled. Skipping.");
    return;
  }

  log.info(
    "Maths quiz feature-flag enabled for user. Fetching experimental quiz patches.",
  );

  const starterQuizPatch = llmPatches.find(
    (p) => p.value.path === "/starterQuiz",
  );

  if (starterQuizPatch) {
    const op = starterQuizPatch.value.op;
    if (op === "remove") {
      await handlePatch(
        preparePatch({
          op,
          path: "/_experimental_starterQuizMathsV0",
        }),
      );
    } else {
      let mathsStarterQuiz: Quiz = await fullQuizService.createBestQuiz(
        "/starterQuiz",
        lessonPlan,
      );
      if (mathsStarterQuiz.length === 0) {
        log.info("No starter quiz found. Creating placeholder starter quiz.");
        mathsStarterQuiz = placeholderQuiz;
      }
      // if the starter quiz contains the text placeholder_quiz_question then we make it into a placeholder quiz.
      if (
        mathsStarterQuiz.some((q) =>
          q.question.includes("placeholder_question_text"),
        )
      ) {
        mathsStarterQuiz = placeholderQuiz;
      }

      if (mathsStarterQuiz) {
        await handlePatch(
          preparePatch({
            path: "/_experimental_starterQuizMathsV0",
            op,
            value: annotateQuestions(mathsStarterQuiz),
          }),
        );
      }
    }
  }

  const exitQuizPatch = llmPatches.find((p) => p.value.path === "/exitQuiz");

  if (exitQuizPatch) {
    const op = exitQuizPatch.value.op;
    if (op === "remove") {
      await handlePatch(
        preparePatch({
          op,
          path: "/_experimental_exitQuizMathsV0",
        }),
      );
    } else {
      // TODO: GCLOMAX - Once this is deprecated we will need logic to not overwrite the original.
      let mathsExitQuiz: Quiz = await fullQuizService.createBestQuiz(
        "/exitQuiz",
        lessonPlan,
      );
      if (mathsExitQuiz.length === 0) {
        log.info("No exit quiz found. Creating placeholder exit quiz.");
        mathsExitQuiz = placeholderQuiz;
      }
      // if the exit quiz contains the text placeholder_quiz_question then we make it into a placeholder quiz.
      if (
        mathsExitQuiz.some((q) =>
          q.question.includes("placeholder_question_text"),
        )
      ) {
        mathsExitQuiz = placeholderQuiz;
      }

      if (mathsExitQuiz) {
        await handlePatch(
          preparePatch({
            path: "/_experimental_exitQuizMathsV0",
            op,
            value: annotateQuestions(mathsExitQuiz),
          }),
        );
      }
    }
  }
}
