// Generated by CodiumAI
import type { JsonPatchDocumentOptional } from "../../protocol/jsonPatchProtocol";
import { PatchEnqueuer } from "./PatchEnqueuer";

const message = {
  type: "patch",
  reasoning: "moderation",
  value: { op: "add", path: "/title", value: "x" },
  status: "complete",
} as unknown as JsonPatchDocumentOptional;

describe("PatchEnqueuer", () => {
  // enqueueInitialField should encode and enqueue a valid patch
  it("should encode and enqueue a valid patch when value is provided", async () => {
    const controller = {
      enqueue: jest.fn(),
    } as unknown as ReadableStreamDefaultController;

    const patchEnqueuer = new PatchEnqueuer(controller);
    const path = "/title" as const;
    const value = "Test Lesson";

    await patchEnqueuer.enqueueInitialField(path, value);

    expect(controller.enqueue).toHaveBeenCalled();
    const expectedPatch = `\n␞\n${JSON.stringify({
      type: "patch",
      reasoning: "generated",
      value: { op: "add", path, value },
      status: "complete",
    })}\n␞\n`;

    expect(controller.enqueue).toHaveBeenCalledWith(expectedPatch);
  });

  it("skips the write when the client has disconnected and the controller is closed", async () => {
    const error = new TypeError("Invalid state: Controller is already closed");
    (error as { code?: string }).code = "ERR_INVALID_STATE";
    const controller = {
      enqueue: jest.fn(() => {
        throw error;
      }),
    } as unknown as ReadableStreamDefaultController;

    const patchEnqueuer = new PatchEnqueuer(controller);

    await expect(
      patchEnqueuer.enqueueMessage(message),
    ).resolves.toBeUndefined();
  });

  it("rethrows when the write fails for any other reason", async () => {
    const controller = {
      enqueue: jest.fn(() => {
        throw new Error("stream write failed");
      }),
    } as unknown as ReadableStreamDefaultController;

    const patchEnqueuer = new PatchEnqueuer(controller);

    await expect(patchEnqueuer.enqueueMessage(message)).rejects.toThrow(
      "stream write failed",
    );
  });

  // enqueuePatch should handle null or undefined value gracefully
  // it("should not enqueue a patch when value is null or undefined", async () => {
  //   const controller = {
  //     enqueue: jest.fn(),
  //   } as unknown as ReadableStreamDefaultController;

  //   const patchEnqueuer = new PatchEnqueuer(controller);
  //   const path = "/test/path";

  //   expect(async () => await patchEnqueuer.enqueuePatch(path, null)).toThrow(
  //     "Value must be provided to enqueue a patch",
  //   );
  //   expect(
  //     async () => await patchEnqueuer.enqueuePatch(path, undefined),
  //   ).toThrow("Value must be provided to enqueue a patch");

  //   expect(controller.enqueue).not.toHaveBeenCalled();
  // });
});
