import { generateAdditionalMaterialModeration } from "@oakai/additional-materials";
import {
  type AdditionalMaterialSchemas,
  actionEnum,
  generateAdditionalMaterialInputSchema,
} from "@oakai/additional-materials/src/documents/additionalMaterials/configSchema";
import { generateAdditionalMaterialObject } from "@oakai/additional-materials/src/documents/additionalMaterials/generateAdditionalMaterialObject";
import {
  type OakOpenAiLessonSummary,
  type OakOpenAiTranscript,
  type OakOpenApiSearchSchema,
  oakOpenAiLessonSummarySchema,
  oakOpenAiTranscriptSchema,
  oakOpenApiSearchSchema,
} from "@oakai/additional-materials/src/documents/schemas/oakOpenApi";
import {
  exportResourceDoc,
  transformDataGlossary,
} from "@oakai/exports/src/exportResourceDoc";
import { aiLogger } from "@oakai/logger";

import * as Sentry from "@sentry/nextjs";
import { ZodError, z } from "zod";

import { protectedProcedure } from "../middleware/auth";
import { router } from "../trpc";

const log = aiLogger("additional-materials");
const OPENAI_AUTH_TOKEN = process.env.OPENAI_AUTH_TOKEN;

export const glossarySchema = z.object({
  glossary: z.array(
    z.object({
      term: z.string().min(1, "Term is required"),
      definition: z.string().min(1, "Definition is required"),
    }),
  ),
});

type GlossarySchema = z.infer<typeof glossarySchema>;

const dummyGlossaryData = {
  glossary: [
    {
      term: "Greenhouse Effect:",
      definition:
        "The trapping of the sun's warmth in a planet's lower atmosphere.",
    },
    {
      term: "Carbon Footprint:",
      definition:
        "The total amount of greenhouse gases generated by our actions.",
    },
    {
      term: "Global Warming:",
      definition:
        "The long-term heating of Earth's climate system due to human activities.",
    },
  ],
};

const title = z.object({
  type: z.literal("title"),
  text: z.string(),
});

const labelValue = z.object({
  label: z.string(),
  value: z.string(),
});
const labelValueArray = z.object({
  type: z.literal("labelValue"),
  items: z.array(labelValue),
});

export const block = z.union([title, labelValueArray]);
export type Block = z.infer<typeof block>;

export const blocksSchema = z.array(block);
export type Blocks = z.infer<typeof blocksSchema>;

// Resource schemas

export const glossaryTemplate = z.union([title, labelValueArray]);

export type GlossaryTemplate = z.infer<typeof glossaryTemplate>;

export const additionalMaterialsRouter = router({
  generateAdditionalMaterial: protectedProcedure
    .input(
      z.object({
        action: z.string(),
        context: z.unknown(),
        documentType: z.string(),
      }),
    )
    .mutation(async ({ ctx, input }): Promise<AdditionalMaterialSchemas> => {
      log.info("fetching additional materials");

      const testExport = await exportResourceDoc({
        snapshotId: "123",
        userEmail: "email",
        onStateChange: (state) => {
          log.info(state);

          // Sentry.addBreadcrumb({
          //   category: "exportWorksheetDocs",
          //   message: "Export state change",
          //   data: state,
          // });
        },
        documentType: "glossary",
        data: dummyGlossaryData,
        transformData: transformDataGlossary<
          GlossarySchema,
          GlossaryTemplate
        >(),
      });

      console.log("testExport", testExport);

      try {
        const result = await generateDocument<
          AdditionalMaterialType,
          AdditionalMaterialPromptContext
        >({
          documentType: action,
          context: {
            lessonPlan,
            message,
            previousOutput,
          },
          documentConfig: additionalMaterialsConfig,
        });

        return result;
      } catch (cause) {
        const TrpcError = new Error("Failed to fetch additional materials", {
          cause,
        });
        log.error("Failed to fetch additional material", cause);
        Sentry.captureException(TrpcError);
        throw TrpcError;
      }
    }),
  generateAdditionalMaterialModeration: protectedProcedure
    .input(
      z.object({
        generation: z.string(),
      }),
    )
    .mutation(async ({ ctx, input }): Promise<string> => {
      const { generation } = input;
      log.info("Fetch additional materials moderation", ctx);

      try {
        const result = await generateAdditionalMaterialModeration(generation);

        return result;
      } catch (cause) {
        const TrpcError = new Error(
          "Failed to fetch additional material moderation",
          { cause },
        );
        log.error("Failed to fetch additional material moderation", cause);
        Sentry.captureException(TrpcError);
        throw TrpcError;
      }
    }),
  fetchOWALessonData: protectedProcedure
    .input(
      z.object({
        lessonSlug: z.string(),
      }),
    )
    .query(
      async ({
        ctx,
        input,
      }): Promise<{
        lessonSummary: OakOpenAiLessonSummary;
        lessonTranscript: OakOpenAiTranscript;
      }> => {
        const { lessonSlug } = input;
        log.info("Fetch oak lesson from oak open api", ctx);

        try {
          const [summaryRes, transcriptRes] = await Promise.all([
            fetch(
              `https://open-api.thenational.academy/api/v0/lessons/${lessonSlug}/summary`,
              {
                method: "GET",
                headers: {
                  Authorization: `Bearer ${OPENAI_AUTH_TOKEN}`,
                  Accept: "application/json",
                },
              },
            ),
            fetch(
              `https://open-api.thenational.academy/api/v0/lessons/${lessonSlug}/transcript`,
              {
                method: "GET",
                headers: {
                  Authorization: `Bearer ${OPENAI_AUTH_TOKEN}`,
                  Accept: "application/json",
                },
              },
            ),
          ]);

          const summaryData = oakOpenAiLessonSummarySchema.parse(
            await summaryRes.json(),
          );
          const transcriptData = oakOpenAiTranscriptSchema.parse(
            await transcriptRes.json(),
          );

          return {
            lessonSummary: summaryData,
            lessonTranscript: transcriptData,
          };
        } catch (cause) {
          const TrpcError = new Error("Failed to fetch oak open ai lesson", {
            cause,
          });
          log.error("Failed to fetch oak open ai lesson", cause);
          Sentry.captureException(TrpcError);
          throw TrpcError;
        }
      },
    ),
  searchOWALesson: protectedProcedure
    .input(
      z.object({
        query: z.string(),
      }),
    )
    .query(async ({ ctx, input }): Promise<OakOpenApiSearchSchema> => {
      const { query } = input;
      log.info("Fetch oak lesson from oak open api");

      try {
        const response = await fetch(
          `https://open-api.thenational.academy/api/v0/search/lessons?q=${query}`,
          {
            method: "GET",
            headers: {
              Authorization: `Bearer ${OPENAI_AUTH_TOKEN}`,
              Accept: "application/json",
            },
          },
        );

        const data = await response.json();

        return oakOpenApiSearchSchema.parse(data);
      } catch (cause) {
        const TrpcError = new Error("Failed to search oak open ai lesson", {
          cause,
        });
        log.error("Failed to search oak open ai lesson", cause);
        Sentry.captureException(TrpcError);
        throw TrpcError;
      }
    }),
});
