import { z } from "zod";

export const proformaTemplateDataSchema = z.object({
  lesson_title: z.string(),
  subject: z.string(),
  key_stage: z.string(),
  topic: z.string().optional(),
  learning_outcome: z.string(),
  learning_cycle_outcome_1: z.string(),
  learning_cycle_outcome_2: z.string().optional(),
  learning_cycle_outcome_3: z.string().optional(),
  prior_knowledge: z.array(z.string()),
  misconception_1: z.string(),
  misconception_2: z.string(),
  misconception_3: z.string(),
  keyword_1: z.string(),
  keyword_2: z.string(),
  keyword_3: z.string().optional(),
  keyword_4: z.string().optional(),
  keyword_5: z.string().optional(),
  keyword_definition_1: z.string(),
  keyword_definition_2: z.string(),
  keyword_definition_3: z.string().optional(),
  keyword_definition_4: z.string().optional(),
  keyword_definition_5: z.string().optional(),
  key_learning_point_1: z.string(),
  key_learning_point_2: z.string().optional(),
  key_learning_point_3: z.string().optional(),
  key_learning_point_4: z.string().optional(),
  starter_quiz_question_1: z.string(),
  starter_quiz_question_1_answer_1: z.string(),
  starter_quiz_question_1_answer_2: z.string(),
  starter_quiz_question_1_answer_3: z.string(),
  starter_quiz_question_2: z.string(),
  starter_quiz_question_2_answer_1: z.string(),
  starter_quiz_question_2_answer_2: z.string(),
  starter_quiz_question_2_answer_3: z.string(),
  starter_quiz_question_3: z.string(),
  starter_quiz_question_3_answer_1: z.string(),
  starter_quiz_question_3_answer_2: z.string(),
  starter_quiz_question_3_answer_3: z.string(),
  starter_quiz_question_4: z.string(),
  starter_quiz_question_4_answer_1: z.string(),
  starter_quiz_question_4_answer_2: z.string(),
  starter_quiz_question_4_answer_3: z.string(),
  starter_quiz_question_5: z.string(),
  starter_quiz_question_5_answer_1: z.string(),
  starter_quiz_question_5_answer_2: z.string(),
  starter_quiz_question_5_answer_3: z.string(),
  starter_quiz_question_6: z.string(),
  starter_quiz_question_6_answer_1: z.string(),
  starter_quiz_question_6_answer_2: z.string(),
  starter_quiz_question_6_answer_3: z.string(),
  exit_quiz_question_1: z.string(),
  exit_quiz_question_1_answer_1: z.string(),
  exit_quiz_question_1_answer_2: z.string(),
  exit_quiz_question_1_answer_3: z.string(),
  exit_quiz_question_2: z.string(),
  exit_quiz_question_2_answer_1: z.string(),
  exit_quiz_question_2_answer_2: z.string(),
  exit_quiz_question_2_answer_3: z.string(),
  exit_quiz_question_3: z.string(),
  exit_quiz_question_3_answer_1: z.string(),
  exit_quiz_question_3_answer_2: z.string(),
  exit_quiz_question_3_answer_3: z.string(),
  exit_quiz_question_4: z.string(),
  exit_quiz_question_4_answer_1: z.string(),
  exit_quiz_question_4_answer_2: z.string(),
  exit_quiz_question_4_answer_3: z.string(),
  exit_quiz_question_5: z.string(),
  exit_quiz_question_5_answer_1: z.string(),
  exit_quiz_question_5_answer_2: z.string(),
  exit_quiz_question_5_answer_3: z.string(),
  exit_quiz_question_6: z.string(),
  exit_quiz_question_6_answer_1: z.string(),
  exit_quiz_question_6_answer_2: z.string(),
  exit_quiz_question_6_answer_3: z.string(),

  learning_cycle_1_title: z.string(),
  learning_cycle_2_title: z.string(),
  learning_cycle_3_title: z.string(),
  learning_cycle_1_text: z.string(),
  cycle_1_spoken_explanation: z.string(),
  cycle_1_check_for_understanding_question_1: z.string(),
  cycle_1_check_for_understanding_question_1_answer_1: z.string(),
  cycle_1_check_for_understanding_question_1_answer_2: z.string(),
  cycle_1_check_for_understanding_question_1_answer_3: z.string(),

  cycle_1_check_for_understanding_question_2: z.string(),
  cycle_1_check_for_understanding_question_2_answer_1: z.string(),
  cycle_1_check_for_understanding_question_2_answer_2: z.string(),
  cycle_1_check_for_understanding_question_2_answer_3: z.string(),

  cycle_1_practice: z.string(),
  cycle_1_feedback: z.string(),

  cycle_2_spoken_explanation: z.string(),
  cycle_2_check_for_understanding_question_1: z.string(),
  cycle_2_check_for_understanding_question_1_answer_1: z.string(),
  cycle_2_check_for_understanding_question_1_answer_2: z.string(),
  cycle_2_check_for_understanding_question_1_answer_3: z.string(),

  cycle_2_check_for_understanding_question_2: z.string(),
  cycle_2_check_for_understanding_question_2_answer_1: z.string(),
  cycle_2_check_for_understanding_question_2_answer_2: z.string(),
  cycle_2_check_for_understanding_question_2_answer_3: z.string(),

  cycle_2_practice: z.string(),
  cycle_2_feedback: z.string(),

  cycle_3_spoken_explanation: z.string(),
  cycle_3_check_for_understanding_question_1: z.string(),
  cycle_3_check_for_understanding_question_1_answer_1: z.string(),
  cycle_3_check_for_understanding_question_1_answer_2: z.string(),
  cycle_3_check_for_understanding_question_1_answer_3: z.string(),

  cycle_3_check_for_understanding_question_2: z.string(),
  cycle_3_check_for_understanding_question_2_answer_1: z.string(),
  cycle_3_check_for_understanding_question_2_answer_2: z.string(),
  cycle_3_check_for_understanding_question_2_answer_3: z.string(),

  cycle_3_practice: z.string(),
  cycle_3_feedback: z.string(),
});

export type ProformaTemplateData = z.infer<typeof proformaTemplateDataSchema>;

export const slidesTemplateDataSchema = z.object({
  lesson_title: z.string(),
  subject_title: z.string(),
  key_stage_title: z.string().nullish(),
  topic_title: z.string().nullish(),
  learning_outcomes: z.string(),
  keywords: z.array(z.string()).nullish(),
  keyword_sentences: z.array(z.string()).nullish(),
  learning_cycle_1_title: z.string(),
  learning_cycle_2_title: z.string().nullish(),
  learning_cycle_3_title: z.string().nullish(),
  learning_cycle_1_text: z.string(),
  learning_cycle_1_image_prompt: z.string(),

  learning_cycle_1_title_long: z.string(),
  learning_cycle_2_title_long: z.string().nullish(),
  learning_cycle_3_title_long: z.string().nullish(),

  learning_cycle_1_check_question_1_question: z.string(),
  learning_cycle_1_question_1_check_answer_1: z.string(),
  learning_cycle_1_question_1_check_answer_2: z.string(),
  learning_cycle_1_question_1_check_answer_3: z.string(),
  learning_cycle_1_check_question_2: z.string(),
  learning_cycle_1_question_2_check_answer_1: z.string(),
  learning_cycle_1_question_2_check_answer_2: z.string(),
  learning_cycle_1_question_2_check_answer_3: z.string(),

  learning_cycle_1_practise: z.string().nullish(),

  learning_cycle_2_text: z.string().nullish(),
  learning_cycle_2_image_prompt: z.string().nullish(),
  learning_cycle_2_question_1_check_question: z.string().nullish(),
  learning_cycle_2_question_1_check_answer_1: z.string().nullish(),
  learning_cycle_2_question_1_check_answer_2: z.string().nullish(),
  learning_cycle_2_question_1_check_answer_3: z.string().nullish(),

  learning_cycle_2_question_2_check_question: z.string().nullish(),
  learning_cycle_2_question_2_check_answer_1: z.string().nullish(),
  learning_cycle_2_question_2_check_answer_2: z.string().nullish(),
  learning_cycle_2_question_2_check_answer_3: z.string().nullish(),

  learning_cycle_2_practise: z.string().nullish(),

  learning_cycle_3_text: z.string().nullish(),
  learning_cycle_3_image_prompt: z.string().nullish(),

  learning_cycle_3_question_1_check_question: z.string().nullish(),
  learning_cycle_3_question_1_check_answer_1: z.string().nullish(),
  learning_cycle_3_question_1_check_answer_2: z.string().nullish(),
  learning_cycle_3_question_1_check_answer_3: z.string().nullish(),

  learning_cycle_3_question_2_check_question: z.string().nullish(),
  learning_cycle_3_question_2_check_answer_1: z.string().nullish(),
  learning_cycle_3_question_2_check_answer_2: z.string().nullish(),
  learning_cycle_3_question_2_check_answer_3: z.string().nullish(),

  learning_cycle_3_practise: z.string().nullish(),
});

export const WARN_IF_MISSING = [
  "learning_cycle_2_title",
  "learning_cycle_2_text",
  "learning_cycle_2_image_prompt",
  "learning_cycle_2_question_1_check_question",
  "learning_cycle_2_question_1_check_answer_1",
  "learning_cycle_2_question_1_check_answer_2",
  "learning_cycle_2_question_1_check_answer_3",
  "learning_cycle_2_question_2_check_question",
  "learning_cycle_2_question_2_check_answer_1",
  "learning_cycle_2_question_2_check_answer_2",
  "learning_cycle_2_question_2_check_answer_3",
  "learning_cycle_2_practise",
];

export type SlidesTemplateData = z.infer<typeof slidesTemplateDataSchema>;

export const lessonQuizSchema = z.object({
  lesson_title: z.string(),
  quiz_type: z.string(),
  question_1: z.string().nullish(),
  question_1_answer_a: z.string().nullish(),
  question_1_answer_b: z.string().nullish(),
  question_1_answer_c: z.string().nullish(),
  question_2: z.string().nullish(),
  question_2_answer_a: z.string().nullish(),
  question_2_answer_b: z.string().nullish(),
  question_2_answer_c: z.string().nullish(),
  question_3: z.string().nullish(),
  question_3_answer_a: z.string().nullish(),
  question_3_answer_b: z.string().nullish(),
  question_3_answer_c: z.string().nullish(),
  question_4: z.string().nullish(),
  question_4_answer_a: z.string().nullish(),
  question_4_answer_b: z.string().nullish(),
  question_4_answer_c: z.string().nullish(),
  question_5: z.string().nullish(),
  question_5_answer_a: z.string().nullish(),
  question_5_answer_b: z.string().nullish(),
  question_5_answer_c: z.string().nullish(),
  question_6: z.string().nullish(),
  question_6_answer_a: z.string().nullish(),
  question_6_answer_b: z.string().nullish(),
  question_6_answer_c: z.string().nullish(),
});

export type LessonQuiz = z.infer<typeof lessonQuizSchema>;
