import { z } from "zod";

export const lessonPlanDocsTemplateSchema = z.object({
  lesson_title: z.string(),
  subject: z.string(),
  key_stage: z.string(),
  topic: z.string().optional(),
  learning_outcome: z.string(),
  learning_cycle_outcome_1: z.string(),
  learning_cycle_outcome_2: z.string().optional(),
  learning_cycle_outcome_3: z.string().optional(),
  prior_knowledge: z.array(z.string()),
  misconception_1: z.string(),
  misconception_2: z.string(),
  misconception_3: z.string(),
  keyword_1: z.string(),
  keyword_2: z.string(),
  keyword_3: z.string().optional(),
  keyword_4: z.string().optional(),
  keyword_5: z.string().optional(),
  keyword_definition_1: z.string(),
  keyword_definition_2: z.string(),
  keyword_definition_3: z.string().optional(),
  keyword_definition_4: z.string().optional(),
  keyword_definition_5: z.string().optional(),
  key_learning_point_1: z.string(),
  key_learning_point_2: z.string().optional(),
  key_learning_point_3: z.string().optional(),
  key_learning_point_4: z.string().optional(),
  starter_quiz_question_1: z.string(),
  starter_quiz_question_1_answer_1: z.string(),
  starter_quiz_question_1_answer_2: z.string(),
  starter_quiz_question_1_answer_3: z.string(),
  starter_quiz_question_2: z.string(),
  starter_quiz_question_2_answer_1: z.string(),
  starter_quiz_question_2_answer_2: z.string(),
  starter_quiz_question_2_answer_3: z.string(),
  starter_quiz_question_3: z.string(),
  starter_quiz_question_3_answer_1: z.string(),
  starter_quiz_question_3_answer_2: z.string(),
  starter_quiz_question_3_answer_3: z.string(),
  starter_quiz_question_4: z.string(),
  starter_quiz_question_4_answer_1: z.string(),
  starter_quiz_question_4_answer_2: z.string(),
  starter_quiz_question_4_answer_3: z.string(),
  starter_quiz_question_5: z.string(),
  starter_quiz_question_5_answer_1: z.string(),
  starter_quiz_question_5_answer_2: z.string(),
  starter_quiz_question_5_answer_3: z.string(),
  starter_quiz_question_6: z.string(),
  starter_quiz_question_6_answer_1: z.string(),
  starter_quiz_question_6_answer_2: z.string(),
  starter_quiz_question_6_answer_3: z.string(),
  exit_quiz_question_1: z.string(),
  exit_quiz_question_1_answer_1: z.string(),
  exit_quiz_question_1_answer_2: z.string(),
  exit_quiz_question_1_answer_3: z.string(),
  exit_quiz_question_2: z.string(),
  exit_quiz_question_2_answer_1: z.string(),
  exit_quiz_question_2_answer_2: z.string(),
  exit_quiz_question_2_answer_3: z.string(),
  exit_quiz_question_3: z.string(),
  exit_quiz_question_3_answer_1: z.string(),
  exit_quiz_question_3_answer_2: z.string(),
  exit_quiz_question_3_answer_3: z.string(),
  exit_quiz_question_4: z.string(),
  exit_quiz_question_4_answer_1: z.string(),
  exit_quiz_question_4_answer_2: z.string(),
  exit_quiz_question_4_answer_3: z.string(),
  exit_quiz_question_5: z.string(),
  exit_quiz_question_5_answer_1: z.string(),
  exit_quiz_question_5_answer_2: z.string(),
  exit_quiz_question_5_answer_3: z.string(),
  exit_quiz_question_6: z.string(),
  exit_quiz_question_6_answer_1: z.string(),
  exit_quiz_question_6_answer_2: z.string(),
  exit_quiz_question_6_answer_3: z.string(),

  learning_cycle_1_title: z.string(),
  learning_cycle_2_title: z.string(),
  learning_cycle_3_title: z.string(),
  learning_cycle_1_text: z.string(),
  cycle_1_spoken_explanation: z.string(),
  cycle_1_check_for_understanding_question_1: z.string(),
  cycle_1_check_for_understanding_question_1_answer_1: z.string(),
  cycle_1_check_for_understanding_question_1_answer_2: z.string(),
  cycle_1_check_for_understanding_question_1_answer_3: z.string(),

  cycle_1_check_for_understanding_question_2: z.string(),
  cycle_1_check_for_understanding_question_2_answer_1: z.string(),
  cycle_1_check_for_understanding_question_2_answer_2: z.string(),
  cycle_1_check_for_understanding_question_2_answer_3: z.string(),

  cycle_1_practice: z.string(),
  cycle_1_feedback: z.string(),

  cycle_2_spoken_explanation: z.string(),
  cycle_2_check_for_understanding_question_1: z.string(),
  cycle_2_check_for_understanding_question_1_answer_1: z.string(),
  cycle_2_check_for_understanding_question_1_answer_2: z.string(),
  cycle_2_check_for_understanding_question_1_answer_3: z.string(),

  cycle_2_check_for_understanding_question_2: z.string(),
  cycle_2_check_for_understanding_question_2_answer_1: z.string(),
  cycle_2_check_for_understanding_question_2_answer_2: z.string(),
  cycle_2_check_for_understanding_question_2_answer_3: z.string(),

  cycle_2_practice: z.string(),
  cycle_2_feedback: z.string(),

  cycle_3_spoken_explanation: z.string(),
  cycle_3_check_for_understanding_question_1: z.string(),
  cycle_3_check_for_understanding_question_1_answer_1: z.string(),
  cycle_3_check_for_understanding_question_1_answer_2: z.string(),
  cycle_3_check_for_understanding_question_1_answer_3: z.string(),

  cycle_3_check_for_understanding_question_2: z.string(),
  cycle_3_check_for_understanding_question_2_answer_1: z.string(),
  cycle_3_check_for_understanding_question_2_answer_2: z.string(),
  cycle_3_check_for_understanding_question_2_answer_3: z.string(),

  cycle_3_practice: z.string(),
  cycle_3_feedback: z.string(),
});

export type LessonPlanDocsTemplateData = z.infer<
  typeof lessonPlanDocsTemplateSchema
>;
