import { useCallback, useState } from "react";

import { Flex } from "@radix-ui/themes";
import * as Sentry from "@sentry/react";

import { DialogTypes } from "@/components/AppComponents/Chat/Chat/types";
import { openSharePage } from "@/components/AppComponents/Chat/Chat/utils";
import ChatButton from "@/components/AppComponents/Chat/ui/chat-button";
import { useLessonChat } from "@/components/ContextProviders/ChatProvider";
import { getLessonTrackingProps } from "@/lib/analytics/helpers";
import useAnalytics from "@/lib/analytics/useAnalytics";
import { trpc } from "@/utils/trpc";

type ShareChatProps = {
  setOpenExportDialog: (open: DialogTypes) => void;
};

const ShareChatDialog = ({ setOpenExportDialog }: Readonly<ShareChatProps>) => {
  const { id, lessonPlan, isShared } = useLessonChat();
  const closeDialog = useCallback(() => {
    setOpenExportDialog("");
  }, [setOpenExportDialog]);

  const { track } = useAnalytics();
  const shareChat = trpc.chat.appSessions.shareChat.useMutation().mutateAsync;

  const [shareLoading, setShareLoading] = useState(false);

  const attemptToShareChat = async () => {
    track.lessonPlanShared({
      ...getLessonTrackingProps({ lesson: lessonPlan }),
      componentType: "go_to_share_page_button",
    });
    if (isShared) {
      openSharePage({ id });
    } else {
      try {
        setShareLoading(true);
        await shareChat({ id });

        openSharePage({ id });
      } catch (error) {
        Sentry.captureException(error, { extra: { chatId: id } });
      } finally {
        setShareLoading(false);
      }
    }
  };

  return (
    <Flex className="h-full w-full" direction="column" justify="between">
      <div>
        <p className="mb-12 text-2xl">Share Chat</p>
        <p className="mb-18">
          Please be aware that while our AI lesson planning tool aims to assist
          educators by generating educational content, it should be used as a
          supplementary resource. The content generated by the tool should
          always be reviewed and adapted to ensure accuracy, relevance, and
          alignment with specific educational standards and objectives.
        </p>
      </div>
      <div className="flex w-full justify-end gap-7">
        <ChatButton variant="secondary" onClick={() => closeDialog()}>
          Cancel
        </ChatButton>
        <ChatButton
          variant="primary"
          onClick={attemptToShareChat}
          disabled={shareLoading}
        >
          Go to share page
        </ChatButton>
      </div>
    </Flex>
  );
};

export default ShareChatDialog;
