export type DialogTypes =
  | ""
  | "share-chat"
  | "feedback"
  | "report-content"
  | "sensitive-moderation-user-comment"
  | "demo-interstitial"
  | "demo-share-locked"
  | "clear-history"
  | "clear-single-chat"
  | "teaching-materials-moderation"
  | "teaching-materials-toxic-moderation"
  | "teaching-materials-threat-detected"
  | "teaching-materials-rate-limit"
  | "teaching-materials-error"
  | "teaching-materials-start-again"
  | "teaching-materials-user-feedback";
