const GOOGLE_SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
const GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY =
  process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY;

if (!GOOGLE_SERVICE_ACCOUNT_EMAIL) {
  throw new Error("GOOGLE_SERVICE_ACCOUNT_EMAIL is required");
}
if (!GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY) {
  throw new Error("GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY is required");
}

export const credentials = {
  client_email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
  private_key: GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY,
};
