DO $$
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM pg_roles
		WHERE rolname = 'app'
    ) THEN
		CREATE ROLE app;
	END IF;
END
$$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM pg_roles
		WHERE rolname = 'retool'
    ) THEN
		CREATE ROLE retool;
	END IF;
END
$$;


DO $$
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM pg_roles
		WHERE rolname = 'sgpostgres'
    ) THEN
		CREATE ROLE sgpostgres;
	END IF;
END
$$;

-- App user
GRANT CONNECT ON DATABASE postgres TO app;
GRANT USAGE ON SCHEMA public TO app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES
FOR USER sgpostgres
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;

-- Retool user
GRANT CONNECT ON DATABASE postgres TO retool;
GRANT USAGE ON SCHEMA public TO retool;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO retool;

ALTER DEFAULT PRIVILEGES
FOR USER sgpostgres
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO retool;
