// Generated by CodiumAI
import { sortIgnoringSpecialChars } from "./sectionToMarkdown";

describe("sortIgnoringSpecialChars", () => {
  // sorts strings alphabetically ignoring special characters with the recommended fix
  it("should sort strings alphabetically ignoring special characters with recommended fix", () => {
    const input = ["- apple", "*banana", " cherry"];
    const expectedOutput = ["- apple", "*banana", " cherry"];
    const result = sortIgnoringSpecialChars(input);
    expect(result).toEqual(expectedOutput);
  });

  // handles empty array input
  it("should return an empty array when input is empty", () => {
    const input: string[] = [];
    const expectedOutput: string[] = [];
    const result = sortIgnoringSpecialChars(input);
    expect(result).toEqual(expectedOutput);
  });
});
