name: Clerk User Cleanup

on:
  schedule:
    # Run daily at 2 AM UTC on staging
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode (no actual deletions)"
        required: true
        default: true
        type: boolean

permissions: {}

jobs:
  clerk-user-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run Clerk User Cleanup on Staging
        run: |
          DRY_RUN="${{ github.event.inputs.dry_run || 'false' }}"
          CLERK_USER_CLEANUP_URL="${{ secrets.CLERK_USER_CLEANUP_URL }}"
          CRON_SECRET="${{ secrets.CRON_SECRET }}"
          VERCEL_AUTOMATION_BYPASS_SECRET="${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}"

          echo "Running clerk user cleanup on staging (dry-run: $DRY_RUN)"

          response=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET" \
            "$CLERK_USER_CLEANUP_URL?dry-run=$DRY_RUN")

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          echo "Response: $body"
          echo "HTTP Status Code: $http_code"

          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          fi

          echo "Clerk user cleanup completed successfully on staging"
