name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    env:
      # You can leverage Vercel Remote Caching with Turbo to speed up your builds
      # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Prisma generate (no engine)
        run: pnpm turbo db-generate:no-engine --cache-dir=".turbo"

      - name: Build, lint and type-check
        run: pnpm turbo lint type-check --cache-dir=".turbo"

      - name: Check workspaces with Manypkg
        run: pnpm manypkg check

      - name: Check formatting with Prettier
        run: pnpm prettier || (echo "::error::Formatting issues detected! Run 'pnpm prettier:fix' to fix them" && exit 1)
