name: Jest

on:
  pull_request:
    branches: ["*"]

jobs:
  test-jest:
    env:
      # You can leverage Vercel Remote Caching with Turbo to speed up your builds
      # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      NODE_OPTIONS: "--experimental-vm-modules"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          # NOTE: We're fixing at 20.18 as 20.19 changes require(esm) logic https://nodejs.org/en/blog/release/v20.19.0
          #       That change is incompatible with jest v29. jest v30 is still in alpha https://github.com/jestjs/jest/pull/15447
          node-version: 20.18
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Generate prisma client
        run: pnpm db-generate:no-engine

      - name: Inject Doppler env vars
        uses: dopplerhq/secrets-fetch-action@v1.2.0
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Run tests
        run: pnpm turbo test --cache-dir=".turbo" -- --maxWorkers=33% --coverage

      # Run only on production branch
      - name: Report coverage to SonarCloud
        if: ${{ github.event.pull_request.merged == true && github.base_ref == 'production' }}
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=packages/**/coverage/lcov.info,apps/nextjs/coverage/lcov.info
