name: Jest

on:
  pull_request:
    branches: ["*"]

jobs:
  test-jest:
    env:
      # You can leverage Vercel Remote Caching with Turbo to speed up your builds
      # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Generate prisma client
        run: pnpm db-generate:no-engine

      - name: Inject Doppler env vars
        uses: dopplerhq/secrets-fetch-action@v1.2.0
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Run tests
        run: pnpm turbo test --cache-dir=".turbo" -- --maxWorkers=33% --coverage
        env:
          I_DOT_AI_ELASTIC_CLOUD_ID: ${{ steps.doppler.outputs.I_DOT_AI_ELASTIC_CLOUD_ID }}
          I_DOT_AI_ELASTIC_KEY: ${{ steps.doppler.outputs.I_DOT_AI_ELASTIC_KEY }}

      # Run only on production branch
      - name: Report coverage to SonarCloud
        if: ${{ github.event.pull_request.merged == true && github.base_ref == 'production' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=packages/**/coverage/lcov.info,apps/nextjs/coverage/lcov.info
